# Generated by Django 5.2.6 on 2025-09-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_favorite_note_tag_alter_note_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='note',
            name='tag',
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
